# Generated by Django 2.2.6 on 2019-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rciApp', '0003_auto_20191020_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date of Publish')),
                ('notice', models.TextField(verbose_name='Notification')),
            ],
        ),
    ]
