# Generated by Django 2.2.6 on 2019-10-20 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rciApp', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_batch',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Batch Timing'),
            preserve_default=False,
        ),
    ]
