# Generated by Django 2.2.6 on 2019-10-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_registration_target',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
            ],
        ),
    ]
