# Generated by Django 2.2.6 on 2019-10-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_registration_target',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
