# Generated by Django 2.2.6 on 2019-10-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_exam_registration_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_registration_target',
            name='date',
        ),
        migrations.AddField(
            model_name='exam_registration_target',
            name='date_of_exam',
            field=models.DateField(auto_now=True, verbose_name='Date of Exam'),
        ),
    ]
