# Generated by Django 2.2.6 on 2019-10-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_auto_20191020_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_registration_Twelve',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
            ],
        ),
    ]
