# Generated by Django 2.2.6 on 2019-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_exam_registration_twelve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exam_registration_Twelve',
            new_name='exam_registration_class_12',
        ),
    ]
