# Generated by Django 2.2.6 on 2019-10-20 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_auto_20191020_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_registration_class_10',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_registration_class_11',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_registration_class_6',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_registration_class_7',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_registration_class_8',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_registration_class_9',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_exam', models.DateField(verbose_name='Date of Exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam_registration_class_12',
            name='date_of_exam',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Exam'),
            preserve_default=False,
        ),
    ]
